export {
  AVAILABLE_CARRIERS,
  centsToMoneyString,
  defaultPackage,
  extractOriginErrors,
  initialOrigin,
  moneyToCents,
  ORIGIN_CONTACT_REQUIRED_MESSAGE,
  SHIPPING_CATEGORIES,
  validateOriginDraft,
  type OriginErrors,
  type OriginField,
  type ShippingDefaultValues,
  type ShippingOriginAddress,
} from "@/modules/settings/presentation/admin/shipping/shippingSettingsConfig";
