// src/config/constants/nexus-thresholds.ts
type BaseThreshold = {
  threshold: number;
  type: "gross" | "taxable" | "none";
  window: "calendar year" | "rolling 12 months" | "none";
  taxable: boolean;
  notes?: string;
  transactions?: number;
  both?: boolean;
};

export const NEXUS_THRESHOLDS: Record<string, BaseThreshold> = {
  AL: { threshold: 250000, type: "gross", window: "rolling 12 months", taxable: true },
  AK: {
    threshold: 100000,
    type: "gross",
    window: "rolling 12 months",
    taxable: false,
    notes: "Local taxes only",
  },
  AZ: { threshold: 100000, type: "gross", window: "calendar year", taxable: true },
  AR: {
    threshold: 100000,
    type: "gross",
    window: "calendar year",
    taxable: true,
    transactions: 200,
  },
  CA: { threshold: 500000, type: "gross", window: "calendar year", taxable: true },
  CO: { threshold: 100000, type: "gross", window: "calendar year", taxable: true },
  CT: {
    threshold: 100000,
    type: "gross",
    window: "calendar year",
    taxable: true,
    transactions: 200,
    both: true,
  },
  DC: {
    threshold: 100000,
    type: "gross",
    window: "calendar year",
    taxable: true,
    transactions: 200,
  },
  FL: { threshold: 100000, type: "taxable", window: "calendar year", taxable: true },
  GA: {
    threshold: 100000,
    type: "gross",
    window: "calendar year",
    taxable: true,
    transactions: 200,
  },
  HI: {
    threshold: 100000,
    type: "gross",
    window: "calendar year",
    taxable: true,
    transactions: 200,
  },
  ID: { threshold: 100000, type: "gross", window: "calendar year", taxable: true },
  IL: { threshold: 100000, type: "gross", window: "rolling 12 months", taxable: true },
  IN: { threshold: 100000, type: "gross", window: "calendar year", taxable: true },
  IA: { threshold: 100000, type: "gross", window: "calendar year", taxable: true },
  KS: { threshold: 100000, type: "gross", window: "calendar year", taxable: true },
  KY: {
    threshold: 100000,
    type: "gross",
    window: "calendar year",
    taxable: true,
    transactions: 200,
  },
  LA: { threshold: 100000, type: "gross", window: "calendar year", taxable: true },
  ME: { threshold: 100000, type: "gross", window: "calendar year", taxable: true },
  MD: {
    threshold: 100000,
    type: "gross",
    window: "calendar year",
    taxable: true,
    transactions: 200,
  },
  MA: { threshold: 100000, type: "gross", window: "calendar year", taxable: false },
  MI: {
    threshold: 100000,
    type: "gross",
    window: "calendar year",
    taxable: true,
    transactions: 200,
  },
  MN: { threshold: 100000, type: "gross", window: "rolling 12 months", taxable: false },
  MS: { threshold: 250000, type: "gross", window: "rolling 12 months", taxable: true },
  MO: { threshold: 100000, type: "gross", window: "rolling 12 months", taxable: true },
  MT: {
    threshold: 0,
    type: "none",
    window: "none",
    taxable: true,
    notes: "No sales tax",
  },
  NE: {
    threshold: 100000,
    type: "gross",
    window: "calendar year",
    taxable: true,
    transactions: 200,
  },
  NV: {
    threshold: 100000,
    type: "gross",
    window: "calendar year",
    taxable: true,
    transactions: 200,
  },
  NH: {
    threshold: 0,
    type: "none",
    window: "none",
    taxable: true,
    notes: "No sales tax",
  },
  NJ: {
    threshold: 100000,
    type: "gross",
    window: "calendar year",
    taxable: false,
    transactions: 200,
  },
  NM: { threshold: 100000, type: "gross", window: "calendar year", taxable: true },
  NY: {
    threshold: 500000,
    type: "gross",
    window: "rolling 12 months",
    taxable: false,
    transactions: 100,
    both: true,
  },
  NC: { threshold: 100000, type: "gross", window: "rolling 12 months", taxable: true },
  ND: { threshold: 100000, type: "gross", window: "rolling 12 months", taxable: true },
  OH: {
    threshold: 100000,
    type: "gross",
    window: "calendar year",
    taxable: true,
    transactions: 200,
  },
  OK: { threshold: 100000, type: "taxable", window: "rolling 12 months", taxable: true },
  OR: {
    threshold: 0,
    type: "none",
    window: "none",
    taxable: true,
    notes: "No sales tax",
  },
  PA: { threshold: 100000, type: "gross", window: "calendar year", taxable: false },
  RI: {
    threshold: 100000,
    type: "gross",
    window: "calendar year",
    taxable: false,
    transactions: 200,
  },
  SC: { threshold: 100000, type: "gross", window: "calendar year", taxable: true },
  SD: { threshold: 100000, type: "gross", window: "calendar year", taxable: true },
  TN: { threshold: 100000, type: "gross", window: "calendar year", taxable: true },
  TX: { threshold: 500000, type: "gross", window: "rolling 12 months", taxable: true },
  UT: { threshold: 100000, type: "gross", window: "calendar year", taxable: true },
  VT: {
    threshold: 100000,
    type: "gross",
    window: "rolling 12 months",
    taxable: false,
    transactions: 200,
  },
  VA: {
    threshold: 100000,
    type: "gross",
    window: "calendar year",
    taxable: true,
    transactions: 200,
  },
  WA: { threshold: 100000, type: "gross", window: "calendar year", taxable: true },
  WV: {
    threshold: 100000,
    type: "gross",
    window: "calendar year",
    taxable: true,
    transactions: 200,
  },
  WI: { threshold: 100000, type: "gross", window: "calendar year", taxable: true },
  WY: { threshold: 100000, type: "gross", window: "calendar year", taxable: true },
} as const;

export const STATE_NAMES: Record<string, string> = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  DC: "District of Columbia",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
};

export const STATE_REGISTRATION_URLS: Record<string, string> = {
  AL: "https://myalabamataxes.alabama.gov",
  AK: "https://arsstc.org", // Alaska has no statewide sales tax (remote sellers register here)
  AZ: "https://aztaxes.gov",
  AR: "https://atap.arkansas.gov",
  CA: "https://onlineservices.cdtfa.ca.gov",
  CO: "https://www.colorado.gov/revenueonline",
  CT: "https://myconnect.ct.gov",
  DC: "https://mytax.dc.gov",
  FL: "https://floridarevenue.com/taxes/registration/Pages/default.aspx",
  GA: "https://gtc.dor.ga.gov",
  HI: "https://hitax.hawaii.gov",
  ID: "https://tax.idaho.gov/tap",
  IL: "https://mytax.illinois.gov",
  IN: "https://intime.dor.in.gov",
  IA: "https://govconnect.iowa.gov",
  KS: "https://www.ksrevenue.org/csc",
  KY: "https://onestop.ky.gov",
  LA: "https://latap.revenue.louisiana.gov",
  ME: "https://portal.maine.gov",
  MD: "https://businessexpress.maryland.gov",
  MA: "https://mtc.dor.state.ma.us",
  MI: "https://mto.treasury.michigan.gov",
  MN: "https://www.revenue.state.mn.us/eservices",
  MS: "https://tap.dor.ms.gov",
  MO: "https://mytax.mo.gov",
  NE: "https://revenue.nebraska.gov/revenue-online",
  NV: "https://tax.nv.gov/TaxCenter",
  NJ: "https://www.njportal.com/DOR/BusinessRegistration",
  NM: "https://tap.state.nm.us",
  NY: "https://www.businessexpress.ny.gov",
  NC: "https://www.ncdor.gov/registering-your-business",
  ND: "https://www.nd.gov/tax/tap",
  OH: "https://gateway.ohio.gov",
  OK: "https://oktap.tax.ok.gov",
  PA: "https://mypath.pa.gov",
  RI: "https://tax.ri.gov/businesses/register",
  SC: "https://mydorway.dor.sc.gov",
  SD: "https://apps.sd.gov/rv23epath",
  TN: "https://tntap.tn.gov",
  TX: "https://comptroller.texas.gov/taxes/permit/",
  UT: "https://tap.tax.utah.gov",
  VT: "https://myvtax.vermont.gov",
  VA: "https://www.virginia.tax",
  WA: "https://mydor.wa.gov",
  WV: "https://mytaxes.wvtax.gov",
  WI: "https://tap.revenue.wi.gov",
  WY: "https://wyifs.wyo.gov",
};

// Stripe documentation URLs for state-specific registration guidance
export const STRIPE_REGISTRATION_GUIDES: Record<string, string> = {
  AL: "https://docs.stripe.com/tax/supported-countries/united-states/alabama",
  AK: "https://docs.stripe.com/tax/supported-countries/united-states/alaska",
  AZ: "https://docs.stripe.com/tax/supported-countries/united-states/arizona",
  AR: "https://docs.stripe.com/tax/supported-countries/united-states/arkansas",
  CA: "https://docs.stripe.com/tax/supported-countries/united-states/california",
  CO: "https://docs.stripe.com/tax/supported-countries/united-states/colorado",
  CT: "https://docs.stripe.com/tax/supported-countries/united-states/connecticut",
  DC: "https://docs.stripe.com/tax/supported-countries/united-states/district-of-columbia",
  FL: "https://docs.stripe.com/tax/supported-countries/united-states/florida",
  GA: "https://docs.stripe.com/tax/supported-countries/united-states/georgia",
  HI: "https://docs.stripe.com/tax/supported-countries/united-states/hawaii",
  ID: "https://docs.stripe.com/tax/supported-countries/united-states/idaho",
  IL: "https://docs.stripe.com/tax/supported-countries/united-states/illinois",
  IN: "https://docs.stripe.com/tax/supported-countries/united-states/indiana",
  IA: "https://docs.stripe.com/tax/supported-countries/united-states/iowa",
  KS: "https://docs.stripe.com/tax/supported-countries/united-states/kansas",
  KY: "https://docs.stripe.com/tax/supported-countries/united-states/kentucky",
  LA: "https://docs.stripe.com/tax/supported-countries/united-states/louisiana",
  ME: "https://docs.stripe.com/tax/supported-countries/united-states/maine",
  MD: "https://docs.stripe.com/tax/supported-countries/united-states/maryland",
  MA: "https://docs.stripe.com/tax/supported-countries/united-states/massachusetts",
  MI: "https://docs.stripe.com/tax/supported-countries/united-states/michigan",
  MN: "https://docs.stripe.com/tax/supported-countries/united-states/minnesota",
  MS: "https://docs.stripe.com/tax/supported-countries/united-states/mississippi",
  MO: "https://docs.stripe.com/tax/supported-countries/united-states/missouri",
  MT: "https://docs.stripe.com/tax/supported-countries/united-states/montana",
  NE: "https://docs.stripe.com/tax/supported-countries/united-states/nebraska",
  NV: "https://docs.stripe.com/tax/supported-countries/united-states/nevada",
  NH: "https://docs.stripe.com/tax/supported-countries/united-states/new-hampshire",
  NJ: "https://docs.stripe.com/tax/supported-countries/united-states/new-jersey",
  NM: "https://docs.stripe.com/tax/supported-countries/united-states/new-mexico",
  NY: "https://docs.stripe.com/tax/supported-countries/united-states/new-york",
  NC: "https://docs.stripe.com/tax/supported-countries/united-states/north-carolina",
  ND: "https://docs.stripe.com/tax/supported-countries/united-states/north-dakota",
  OH: "https://docs.stripe.com/tax/supported-countries/united-states/ohio",
  OK: "https://docs.stripe.com/tax/supported-countries/united-states/oklahoma",
  OR: "https://docs.stripe.com/tax/supported-countries/united-states/oregon",
  PA: "https://docs.stripe.com/tax/supported-countries/united-states/pennsylvania",
  RI: "https://docs.stripe.com/tax/supported-countries/united-states/rhode-island",
  SC: "https://docs.stripe.com/tax/supported-countries/united-states/south-carolina",
  SD: "https://docs.stripe.com/tax/supported-countries/united-states/south-dakota",
  TN: "https://docs.stripe.com/tax/supported-countries/united-states/tennessee",
  TX: "https://docs.stripe.com/tax/supported-countries/united-states/texas",
  UT: "https://docs.stripe.com/tax/supported-countries/united-states/utah",
  VT: "https://docs.stripe.com/tax/supported-countries/united-states/vermont",
  VA: "https://docs.stripe.com/tax/supported-countries/united-states/virginia",
  WA: "https://docs.stripe.com/tax/supported-countries/united-states/washington",
  WV: "https://docs.stripe.com/tax/supported-countries/united-states/west-virginia",
  WI: "https://docs.stripe.com/tax/supported-countries/united-states/wisconsin",
  WY: "https://docs.stripe.com/tax/supported-countries/united-states/wyoming",
};

export const PRODUCT_TAX_CODES: Record<string, string> = {
  sneakers: "txcd_30011000",
  clothing: "txcd_30011000",
  accessories: "txcd_30060010",
  electronics: "txcd_34020027",
};

export type StateCode = keyof typeof NEXUS_THRESHOLDS;
export type NexusThreshold = (typeof NEXUS_THRESHOLDS)[StateCode];
